### ISSUE TITLE
footnote dialog not opening 

### ISSUE THREAD

**Issue by marco-land** [johannschopplich/kirby-writer-marks#1]
hi johann,

great plugin; might be really helpful! i've tried to install it and get the quote icon showing up, but when I click on it nothing happens. any idea why this might be happening?

**Comment by johannschopplich** [comment]
Hi Marco,

I experienced this bug as well, but haven't found neither a solution, nor the source for this problem. The same code but baked into the panel directly is working just fine. No idea for now why this ain't working...

**Comment by marco-land** [comment]
Ah I see, this is weird. How do you bake it into the panel directly? I did not quite understand this from the description yet. In my `kirby/panel` folder I only have the `dist` folder.

**Comment by johannschopplich** [comment]
Fixed in https://github.com/johannschopplich/kirby-writer-marks/commit/16e27ab47584e83c8fd1a9618e150ebe967f7aae.
