### ISSUE TITLE
Footnote icon not showing up

### ISSUE THREAD

**Issue by manspeterson** [johannschopplich/kirby-writer-marks#3]
Hey,

Thanks for your wonderful job. 

Just tried to install this patch and plugin for the first time today on a new empty project running the latest version of Kirby. 

After running the patch successfully the footnote mark is registered within `window.panel.plugins.marks`. However the footnote icon does not show up among the other default marks while selecting text. 

Could Kirby have introduced a breaking change in their latest versions or am I just missing something?

**Comment by herrajon** [comment]
@johannschopplich Could be worth mentioning too clear the browser cache as well.
