### ISSUE TITLE
Handle Popup/Dialog

### ISSUE THREAD

**Issue by marco-land** [johannschopplich/kirby-writer-marks#5]
Great plugin and very nice to see how it has improved over the last months!

One thing that is not quite clear to me is how to handle pop ups/dialogs with a custom mark. For example, the link mark has the input fields url / title / open in new window.

I tried to compare/understand the original [link.js](https://github.com/getkirby/kirby/blob/0a1f15d39a4be3e5ab6fae868d2ff607fab3dce9/panel/src/components/Forms/Writer/Marks/Link.js) file and also noticed the [Dialog folder](https://github.com/getkirby/kirby/tree/0a1f15d39a4be3e5ab6fae868d2ff607fab3dce9/panel/src/components/Forms/Writer/Dialogs) but do not understand yet how to add these.

In my opinion the example footnote mark is also missing this part because the footnotes are missing content otherwise, or am I overseeing something? If this is already possible it might be helpful to add this to the footnote example.

**Comment by johannschopplich** [comment]
Hi there,

thanks for the flowers! The footnote example mark uses the custom element `<article-footnote />` and doesn't need a dialog element. It is up to you to parse footnotes in your article. The footnote mark probably won't be extended; its current scope should stay lean and comprehensible.

For a more comprehensive example, I highly recommend [kirby-extended-writer](https://github.com/coralic/kirby-extended-writer), which is built upon this plugin!
