### ISSUE TITLE
Font styles in Mark destroys Mark

### ISSUE THREAD

**Issue by jonasholfeld** [johannschopplich/kirby-writer-marks#7]
If I try to add italic / bold / underline / crossed text inside a mark, the plugin automatically splits the mark into three sections so that the highlighted text is now in its own mark:
<img width="644" alt="Bildschirmfoto 2022-04-13 um 10 42 45" src="https://user-images.githubusercontent.com/52667313/163136899-17f18114-78cd-4835-8f75-08ba4b8e5ad4.png">

**Comment by johannschopplich** [comment]
You will have to adapt the schema to your needs:

https://github.com/johannschopplich/kirby-writer-marks/blob/fc700915ef2d4cb52f92ac0def1e3b9235ba94a2/src/Marks/Footnote.js#L19

The custom footnote mark doesn't allow italic text. The mark as well as this repo is just an example. Thus, I will close this.
